from app.database import SessionLocal
from app.models import Researcher


researchers = [
    {
        "name": "Dr. Anil Kumar",
        "department": "Computer Science and Engineering",
        "designation": "Professor",
        "experience": 10,
        "research_areas": "Artificial Intelligence, Machine Learning, Computer Vision",
        "expertise": "Deep Learning, Medical Image Analysis, Computer Vision",
        "skills": "Python, TensorFlow, OpenCV, PyTorch",
        "publications": "Deep Learning for Medical Image Analysis; Computer Vision Based Disease Detection",
        "projects": "AI-based Medical Image Classification; Smart Healthcare System",
    },
    {
        "name": "Dr. Priya Sharma",
        "department": "Computer Science and Engineering",
        "designation": "Associate Professor",
        "experience": 8,
        "research_areas": "Natural Language Processing, Generative AI",
        "expertise": "NLP, LLMs, Text Mining",
        "skills": "Python, NLP, Transformers, PyTorch",
        "publications": "Transformer Models for Text Classification; NLP Applications",
        "projects": "Intelligent Document Analysis",
    },
    {
        "name": "Dr. Rahul Singh",
        "department": "Electronics and Communication Engineering",
        "designation": "Professor",
        "experience": 12,
        "research_areas": "IoT, Embedded Systems, Robotics",
        "expertise": "IoT, Robotics, Sensor Networks",
        "skills": "C++, Python, Arduino, Raspberry Pi",
        "publications": "IoT-Based Smart Systems; Autonomous Robotics",
        "projects": "Smart Campus IoT",
    },
    {
        "name": "Dr. Neha Verma",
        "department": "Computer Science and Engineering",
        "designation": "Assistant Professor",
        "experience": 6,
        "research_areas": "Data Science, Machine Learning, Predictive Analytics",
        "expertise": "Data Mining, Statistical Learning, Predictive Modeling",
        "skills": "Python, Pandas, Scikit-learn, SQL",
        "publications": "Predictive Analytics for Student Performance; Machine Learning Applications",
        "projects": "Student Success Prediction System",
    },
    {
        "name": "Dr. Arjun Mehta",
        "department": "Computer Science and Engineering",
        "designation": "Professor",
        "experience": 15,
        "research_areas": "Cybersecurity, Network Security, Blockchain",
        "expertise": "Intrusion Detection, Cryptography, Blockchain Security",
        "skills": "Python, Java, Linux, Wireshark",
        "publications": "Machine Learning for Intrusion Detection; Secure Blockchain Networks",
        "projects": "AI-Based Network Threat Detection",
    },
    {
        "name": "Dr. Sneha Reddy",
        "department": "Computer Science and Engineering",
        "designation": "Associate Professor",
        "experience": 9,
        "research_areas": "Cloud Computing, Distributed Systems, Edge Computing",
        "expertise": "Cloud Architecture, Distributed Computing, Edge AI",
        "skills": "Python, Java, Docker, Kubernetes, AWS",
        "publications": "Edge Computing for Intelligent Applications",
        "projects": "Cloud-Based AI Platform",
    },
    {
        "name": "Dr. Vikram Joshi",
        "department": "Electronics and Communication Engineering",
        "designation": "Professor",
        "experience": 14,
        "research_areas": "Wireless Communication, 5G, IoT",
        "expertise": "5G Networks, Wireless Sensor Networks, Communication Systems",
        "skills": "MATLAB, Python, C++, NS3",
        "publications": "5G Enabled IoT Communication; Wireless Sensor Networks",
        "projects": "Smart Wireless Infrastructure",
    },
    {
        "name": "Dr. Aisha Khan",
        "department": "Computer Science and Engineering",
        "designation": "Assistant Professor",
        "experience": 5,
        "research_areas": "Computer Vision, Deep Learning, Image Processing",
        "expertise": "Object Detection, Image Segmentation, CNNs",
        "skills": "Python, OpenCV, PyTorch, TensorFlow",
        "publications": "Deep Learning for Object Detection",
        "projects": "Real-Time Vision Analytics",
    },
    {
        "name": "Dr. Karan Malhotra",
        "department": "Computer Science and Engineering",
        "designation": "Associate Professor",
        "experience": 11,
        "research_areas": "Software Engineering, DevOps, Software Testing",
        "expertise": "Continuous Integration, Automated Testing, Software Quality",
        "skills": "Java, Python, Docker, Jenkins, Git",
        "publications": "Automated Software Testing; DevOps Practices",
        "projects": "Intelligent CI/CD Quality Platform",
    },
    {
        "name": "Dr. Meera Iyer",
        "department": "Computer Science and Engineering",
        "designation": "Professor",
        "experience": 16,
        "research_areas": "Artificial Intelligence, Knowledge Representation, Expert Systems",
        "expertise": "Knowledge Graphs, Reasoning Systems, AI Planning",
        "skills": "Python, RDF, SPARQL, Neo4j",
        "publications": "Knowledge Graphs for Intelligent Systems",
        "projects": "University Knowledge Graph",
    },
    {
        "name": "Dr. Rohan Gupta",
        "department": "Computer Science and Engineering",
        "designation": "Assistant Professor",
        "experience": 4,
        "research_areas": "Recommender Systems, Machine Learning, Data Mining",
        "expertise": "Collaborative Filtering, Recommendation Algorithms",
        "skills": "Python, Scikit-learn, Pandas, SQL",
        "publications": "Personalized Recommendation Using Machine Learning",
        "projects": "Intelligent Academic Recommendation System",
    },
    {
        "name": "Dr. Kavita Nair",
        "department": "Information Technology",
        "designation": "Associate Professor",
        "experience": 10,
        "research_areas": "Big Data, Data Analytics, Data Engineering",
        "expertise": "Data Pipelines, Distributed Data Processing, Analytics",
        "skills": "Python, Spark, Hadoop, SQL",
        "publications": "Scalable Big Data Analytics",
        "projects": "University Data Analytics Platform",
    },
    {
        "name": "Dr. Aditya Rao",
        "department": "Computer Science and Engineering",
        "designation": "Professor",
        "experience": 13,
        "research_areas": "Natural Language Processing, Information Retrieval, Search",
        "expertise": "Semantic Search, Text Retrieval, Question Answering",
        "skills": "Python, Transformers, Elasticsearch, NLP",
        "publications": "Semantic Search Using Transformer Models",
        "projects": "Intelligent University Search Engine",
    },
    {
        "name": "Dr. Pooja Kapoor",
        "department": "Computer Science and Engineering",
        "designation": "Assistant Professor",
        "experience": 5,
        "research_areas": "Human Computer Interaction, AI, User Experience",
        "expertise": "UX Research, Intelligent Interfaces, Usability",
        "skills": "Python, Figma, JavaScript, React",
        "publications": "Human-Centered AI Interfaces",
        "projects": "Adaptive Student Learning Interface",
    },
    {
        "name": "Dr. Sameer Bhatia",
        "department": "Electronics and Communication Engineering",
        "designation": "Associate Professor",
        "experience": 9,
        "research_areas": "Robotics, Autonomous Systems, Computer Vision",
        "expertise": "Robot Navigation, Sensor Fusion, Autonomous Control",
        "skills": "C++, Python, ROS, OpenCV",
        "publications": "Vision-Based Autonomous Navigation",
        "projects": "Autonomous Campus Robot",
    },
    {
        "name": "Dr. Nisha Patel",
        "department": "Information Technology",
        "designation": "Assistant Professor",
        "experience": 6,
        "research_areas": "Database Systems, Data Management, Big Data",
        "expertise": "Database Optimization, Distributed Databases",
        "skills": "SQL, PostgreSQL, Python, MongoDB",
        "publications": "Efficient Query Processing in Distributed Databases",
        "projects": "Scalable Academic Data Management",
    },
    {
        "name": "Dr. Saurabh Jain",
        "department": "Computer Science and Engineering",
        "designation": "Professor",
        "experience": 17,
        "research_areas": "Cloud Security, Cybersecurity, Privacy",
        "expertise": "Cloud Threat Detection, Privacy Preserving Computing",
        "skills": "Python, Linux, Docker, Kubernetes",
        "publications": "Security and Privacy in Cloud Computing",
        "projects": "Secure Cloud Infrastructure",
    },
    {
        "name": "Dr. Divya Menon",
        "department": "Computer Science and Engineering",
        "designation": "Associate Professor",
        "experience": 8,
        "research_areas": "Federated Learning, Privacy-Preserving AI, Machine Learning",
        "expertise": "Federated Optimization, Secure Machine Learning",
        "skills": "Python, PyTorch, TensorFlow, Cryptography",
        "publications": "Privacy-Preserving Federated Learning",
        "projects": "Federated Healthcare AI",
    },
    {
        "name": "Dr. Manish Agarwal",
        "department": "Electronics and Communication Engineering",
        "designation": "Professor",
        "experience": 18,
        "research_areas": "Embedded Systems, VLSI, IoT",
        "expertise": "Embedded Hardware, Digital Systems, Smart Sensors",
        "skills": "C, C++, Verilog, Arduino",
        "publications": "Low-Power Embedded Systems for IoT",
        "projects": "Smart Sensor Network",
    },
    {
        "name": "Dr. Ritu Chawla",
        "department": "Computer Science and Engineering",
        "designation": "Assistant Professor",
        "experience": 5,
        "research_areas": "Educational Data Mining, Machine Learning, Learning Analytics",
        "expertise": "Student Modeling, Learning Analytics, Predictive Models",
        "skills": "Python, Pandas, Scikit-learn, SQL",
        "publications": "Machine Learning for Student Performance Analysis",
        "projects": "Early Academic Risk Prediction",
    },
    {
        "name": "Dr. Harish Kumar",
        "department": "Mechanical Engineering",
        "designation": "Professor",
        "experience": 20,
        "research_areas": "Robotics, Automation, Industrial AI",
        "expertise": "Industrial Robotics, Predictive Maintenance",
        "skills": "MATLAB, Python, PLC, C++",
        "publications": "AI-Based Predictive Maintenance",
        "projects": "Intelligent Manufacturing System",
    },
    {
        "name": "Dr. Simran Kaur",
        "department": "Computer Science and Engineering",
        "designation": "Assistant Professor",
        "experience": 4,
        "research_areas": "Generative AI, NLP, Large Language Models",
        "expertise": "Prompt Engineering, RAG, LLM Applications",
        "skills": "Python, Transformers, LangChain, PyTorch",
        "publications": "Retrieval-Augmented Generation for Academic Search",
        "projects": "AI Research Assistant",
    },
    {
        "name": "Dr. Deepak Verma",
        "department": "Computer Science and Engineering",
        "designation": "Associate Professor",
        "experience": 12,
        "research_areas": "Algorithms, Optimization, Artificial Intelligence",
        "expertise": "Combinatorial Optimization, Metaheuristics",
        "skills": "C++, Python, MATLAB, OR-Tools",
        "publications": "Optimization Techniques for Intelligent Systems",
        "projects": "Resource Allocation Optimization",
    },
    {
        "name": "Dr. Shalini Bose",
        "department": "Biotechnology",
        "designation": "Professor",
        "experience": 14,
        "research_areas": "Bioinformatics, Computational Biology, Machine Learning",
        "expertise": "Genomic Data Analysis, Protein Prediction",
        "skills": "Python, R, Biopython, Machine Learning",
        "publications": "Machine Learning for Genomic Analysis",
        "projects": "AI-Based Disease Biomarker Discovery",
    },
    {
        "name": "Dr. Abhishek Roy",
        "department": "Computer Science and Engineering",
        "designation": "Assistant Professor",
        "experience": 6,
        "research_areas": "Blockchain, Distributed Systems, Web3",
        "expertise": "Smart Contracts, Decentralized Applications",
        "skills": "Solidity, JavaScript, Python, Ethereum",
        "publications": "Blockchain-Based Decentralized Applications",
        "projects": "Secure Academic Credential System",
    },
    {
        "name": "Dr. Tanvi Shah",
        "department": "Computer Science and Engineering",
        "designation": "Associate Professor",
        "experience": 9,
        "research_areas": "Speech Processing, NLP, Artificial Intelligence",
        "expertise": "Speech Recognition, Audio Classification",
        "skills": "Python, PyTorch, Whisper, Librosa",
        "publications": "Deep Learning for Speech Recognition",
        "projects": "Multilingual Speech Assistant",
    },
    {
        "name": "Dr. Mohit Srivastava",
        "department": "Information Technology",
        "designation": "Professor",
        "experience": 15,
        "research_areas": "Information Security, Digital Forensics, Cybersecurity",
        "expertise": "Malware Analysis, Digital Evidence, Network Security",
        "skills": "Python, Linux, Wireshark, Kali Linux",
        "publications": "Machine Learning for Malware Detection",
        "projects": "Intelligent Cyber Forensics Platform",
    },
    {
        "name": "Dr. Ananya Das",
        "department": "Computer Science and Engineering",
        "designation": "Assistant Professor",
        "experience": 5,
        "research_areas": "Time Series Forecasting, Machine Learning, AI",
        "expertise": "Forecasting, Anomaly Detection, Statistical Modeling",
        "skills": "Python, Pandas, Scikit-learn, TensorFlow",
        "publications": "Deep Learning for Time Series Forecasting",
        "projects": "Intelligent Demand Forecasting",
    },
    {
        "name": "Dr. Vivek Sharma",
        "department": "Civil Engineering",
        "designation": "Professor",
        "experience": 19,
        "research_areas": "Smart Cities, IoT, Sustainable Infrastructure",
        "expertise": "Smart Infrastructure, Urban Analytics, Sensor Networks",
        "skills": "Python, IoT, GIS, MATLAB",
        "publications": "IoT-Based Smart City Infrastructure",
        "projects": "Intelligent Smart Campus Infrastructure",
    },
    {
        "name": "Dr. Isha Thomas",
        "department": "Computer Science and Engineering",
        "designation": "Associate Professor",
        "experience": 10,
        "research_areas": "Reinforcement Learning, Robotics, Autonomous Systems",
        "expertise": "Deep Reinforcement Learning, Robot Control",
        "skills": "Python, PyTorch, OpenAI Gym, ROS",
        "publications": "Deep Reinforcement Learning for Autonomous Robots",
        "projects": "Autonomous Navigation Using Reinforcement Learning",
    },
]


db = SessionLocal()

try:
    # Remove existing demo researchers
    db.query(Researcher).delete()
    db.commit()

    for data in researchers:
        researcher = Researcher(
            name=data["name"],
            department=data["department"],
            designation=data["designation"],
            experience=data["experience"],
            research_areas=data["research_areas"],
            expertise=data["expertise"],
            skills=data["skills"],
            publications=data["publications"],
            projects=data["projects"],
            profile_url="https://example.com/researcher",
        )

        db.add(researcher)

    db.commit()

    print(f"Successfully added {len(researchers)} researchers.")

finally:
    db.close()